name: test_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_material_pickers: ^3.3.0
  currency_picker: ^2.0.15
  file_picker: ^5.2.1

  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets: 
    - assets/images/
  uses-material-design: true